services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:postgresql_db
    volumes:
      - lucene-indexes:/data/lucene-indexes
    environment:
      - PGHOST=postgresql_db
      - PGUSER=postgres
      - PGPORT=5432
      - PGDATABASE=ks-db
      - PGPASSWORD=${PGPASSWORD}
      - CLOUDINARY_URL=${CLOUDINARY_URL}

  postgresql_db:
    image: "postgres:15-alpine"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ks-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}

volumes:
  db-data:
  lucene-indexes:
