#file: noinspection SpellCheckingInspection
spring:
  application:
    name: kishka-strybaie
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            directory:
              root: /data/lucene-indexes/
  devtools:
    restart:
      enabled: true